const batizadoFolder = 'images/BATIZADO CATARINA 26-07-25';
const cha2023Folder = 'images/CH\u00c1 REVELA\u00c7\u00c3O 12-11-23';
const cha2024Folder = 'images/CHA REVELA\u00c7\u00c3O 28-04-24';
const formaturaFolder = 'images/FORMATURA CEFET - TURMA MECANICA 2025';

window.contactImagePaths = [
  `${batizadoFolder}/SANTIDADEEMFOCO-001_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-003_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-004_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-007_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-013_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-023_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-027_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-029_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-037_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-041_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-048_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-054_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-060_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-074_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-076_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-077_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-078_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-081_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-083_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-086_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-087_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-093_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-097_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-102_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-103_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-104_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-107_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-112_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-130_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-181_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-199_resultado.avif`,
  `${batizadoFolder}/SANTIDADEEMFOCO-214_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__206_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__224_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__231_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__235_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__240_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__245_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__251_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__257_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__263_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__269_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__275_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__280_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__283_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__287_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__293_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__297_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__3_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__301_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__331_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__336_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__339_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__345_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__358_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__359_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__361_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__369_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__370_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__371_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__372_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__373_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__429_resultado.avif`,
  `${cha2023Folder}/@GUILHERME_FOTOGRAFO__440_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__1_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__116_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__117_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__120_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__123_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__129_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__13_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__136_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__16_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__17_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__185_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__23_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__257_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__50_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__54_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__7_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__71_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__91_resultado.avif`,
  `${cha2024Folder}/@GUILHERME_FOTOGRAFO__resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_103_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_108_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_111_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_117_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_122_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_129_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_136_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_143_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_147_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_197_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_206_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_214_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_219_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_259_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_284_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_287_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_288_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_291_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_324_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_325_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_326_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_574_resultado.avif`,
  `${formaturaFolder}/LHERME FILMS_resultado.avif`
];
